### 방 만들기 요청 (성공 케이스)
POST http://localhost:8080/api/rooms
Content-Type: application/json

{
  "nickname": "su"
}

###
POST http://localhost:8080/api/rooms/join
Content-Type: application/json

{
  "joinCode" : "406478",
  "nickname": "temp1"
}

###
GET http://localhost:8080/api/rooms/3a35609d-2b76-414d-92b8-b19a824c9c41
Content-Type: application/json

