/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dev/PoliceEscapeCountdownModal`; params?: Router.UnknownInputParams; } | { pathname: `/dev/ThiefEscapeTapModal`; params?: Router.UnknownInputParams; } | { pathname: `/entry/createRoom`; params?: Router.UnknownInputParams; } | { pathname: `/entry/joinRoom`; params?: Router.UnknownInputParams; } | { pathname: `/entry/main`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/game/roleCheck`; params?: Router.UnknownInputParams; } | { pathname: `/game/role_check`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | { pathname: `/room/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/PoliceEscapeCountdownModal`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/ThiefEscapeTapModal`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/createRoom`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/joinRoom`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/main`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/game/roleCheck`; params?: Router.UnknownOutputParams; } | { pathname: `/game/role_check`; params?: Router.UnknownOutputParams; } | { pathname: `/room`; params?: Router.UnknownOutputParams; } | { pathname: `/room/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/dev/PoliceEscapeCountdownModal${`?${string}` | `#${string}` | ''}` | `/dev/ThiefEscapeTapModal${`?${string}` | `#${string}` | ''}` | `/entry/createRoom${`?${string}` | `#${string}` | ''}` | `/entry/joinRoom${`?${string}` | `#${string}` | ''}` | `/entry/main${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/game/roleCheck${`?${string}` | `#${string}` | ''}` | `/game/role_check${`?${string}` | `#${string}` | ''}` | `/room${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dev/PoliceEscapeCountdownModal`; params?: Router.UnknownInputParams; } | { pathname: `/dev/ThiefEscapeTapModal`; params?: Router.UnknownInputParams; } | { pathname: `/entry/createRoom`; params?: Router.UnknownInputParams; } | { pathname: `/entry/joinRoom`; params?: Router.UnknownInputParams; } | { pathname: `/entry/main`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/game/roleCheck`; params?: Router.UnknownInputParams; } | { pathname: `/game/role_check`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | `/room/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/room/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
    }
  }
}
