spring.application.name=gyeong-do-go

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# SQL logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# 기본 프로필을 local로 둠
spring.profiles.default=local