# DB (???? ?? IP ??)
spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis (???? ?? IP ??)
spring.data.redis.host=redis
spring.data.redis.port=6379
# ?? ???? ????? ????? ?? ??
# spring.data.redis.password=????

# JPA
spring.jpa.hibernate.ddl-auto=update